"""Record the presentable Phase 0 CLI transcript from actual subprocess results."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

import yaml


def run_command(repository: Path, arguments: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["uv", "run", "wms", *arguments],
        cwd=repository,
        check=False,
        capture_output=True,
        text=True,
    )


def record(
    lines: list[str], repository: Path, display: str, arguments: list[str]
) -> subprocess.CompletedProcess[str]:
    completed = run_command(repository, arguments)
    lines.extend((f"$ uv run wms {display}", f"exit: {completed.returncode}"))
    if completed.stdout.strip():
        lines.append(completed.stdout.strip().replace(str(repository), "<REPO>"))
    if completed.stderr.strip() and completed.returncode != 0:
        lines.append(completed.stderr.strip().splitlines()[-1])
    lines.append("")
    return completed


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=Path("docs/phase0_cli_transcript.txt"))
    arguments = parser.parse_args()
    repository = Path.cwd()
    generated = repository / "artifacts" / "transcript-inputs"
    generated.mkdir(parents=True, exist_ok=True)

    smoke_raw = yaml.safe_load((repository / "configs" / "smoke.yaml").read_text(encoding="utf-8"))
    if not isinstance(smoke_raw, dict) or not isinstance(smoke_raw.get("run"), dict):
        raise RuntimeError("smoke configuration has an unexpected shape")
    smoke_raw["run"]["root"] = "artifacts/transcript-runs"
    valid_config = generated / "smoke.yaml"
    valid_config.write_text(yaml.safe_dump(smoke_raw, sort_keys=False), encoding="utf-8")
    invalid_raw = dict(smoke_raw)
    invalid_raw["run"] = dict(smoke_raw["run"])
    invalid_raw["run"]["max_steps"] = 0
    invalid_config = generated / "invalid.yaml"
    invalid_config.write_text(yaml.safe_dump(invalid_raw, sort_keys=False), encoding="utf-8")

    lines = [
        "Phase 0 recorded CLI transcript",
        "Generated by scripts/record_phase0_transcript.py; stdout is captured verbatim",
        "except that the repository path is normalized to <REPO>.",
        "Structured diagnostic stderr is omitted unless a command fails validation.",
        "",
    ]
    record(
        lines,
        repository,
        "solve --config <GENERATED_CONFIG> --proposer mock --run-id transcript-resume "
        "--interrupt-after 2",
        [
            "solve",
            "--config",
            str(valid_config),
            "--proposer",
            "mock",
            "--run-id",
            "transcript-resume",
            "--interrupt-after",
            "2",
        ],
    )
    record(
        lines,
        repository,
        "solve --resume transcript-resume --runs-root artifacts/transcript-runs",
        [
            "solve",
            "--resume",
            "transcript-resume",
            "--runs-root",
            "artifacts/transcript-runs",
        ],
    )
    record(
        lines,
        repository,
        "replay --run transcript-resume --runs-root artifacts/transcript-runs",
        [
            "replay",
            "--run",
            "transcript-resume",
            "--runs-root",
            "artifacts/transcript-runs",
        ],
    )
    first = record(
        lines,
        repository,
        "solve --config <GENERATED_CONFIG> --proposer mock --run-id transcript-seed-a",
        [
            "solve",
            "--config",
            str(valid_config),
            "--proposer",
            "mock",
            "--run-id",
            "transcript-seed-a",
        ],
    )
    second = record(
        lines,
        repository,
        "solve --config <GENERATED_CONFIG> --proposer mock --run-id transcript-seed-b",
        [
            "solve",
            "--config",
            str(valid_config),
            "--proposer",
            "mock",
            "--run-id",
            "transcript-seed-b",
        ],
    )
    first_result = json.loads(first.stdout)
    second_result = json.loads(second.stdout)
    hashes_equal = first_result["event_payload_hashes"] == second_result["event_payload_hashes"]
    lines.extend((f"same-seed event payload hashes equal: {str(hashes_equal).lower()}", ""))

    invalid = record(
        lines,
        repository,
        "solve --config <INVALID_CONFIG> --proposer mock --run-id transcript-invalid",
        [
            "solve",
            "--config",
            str(invalid_config),
            "--proposer",
            "mock",
            "--run-id",
            "transcript-invalid",
        ],
    )
    invalid_run = repository / "artifacts" / "transcript-runs" / "transcript-invalid"
    lines.append(f"invalid run artifact exists: {str(invalid_run.exists()).lower()}")

    if not hashes_equal or invalid.returncode == 0 or invalid_run.exists():
        raise RuntimeError("a Phase 0 transcript gate failed")
    output = repository / arguments.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(output.relative_to(repository))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
